### ISSUE TITLE
Project future

### ISSUE THREAD

**Issue by beeman** [beeman/createvm.sh#1]
This was a pet-project some years ago and at this point I'm not sure what do do with it. 

@waterkip Finally I moved this script to GitHub. Are you still using it? Is there still need for the Python-specific branches?

**Comment by waterkip** [comment]
I don't use it (anymore). I will fork it tho ;) 
Re the python specific branch, I never used the python branch (I think). 

Je kan trouwens mijn slacker-createvm branch droppen, ik heb de shizzle geforked, mocht ik nieuwe features bouwen dan krijg je vanzelf een trekverzoek van me :)

**Comment by beeman** [comment]
Oke, great. I will just leave it here as-is, without slacker-createvm :)...
